---
- hosts: all
  become_user: root
  become_method: sudo
  roles:
    - role: env-common-scheleaap
      tags: common

- hosts: desktop
  become_user: root
  become_method: sudo
  roles:
#    - role: work
    - role: env-desktop-scheleaap
      tags: desktop

